-- ============================================
-- Exercise 5 : Triggers
-- ============================================

-------------------------------------------------
-- Create AuditLog Table
-------------------------------------------------

CREATE TABLE AuditLog (
    LogID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TransactionID NUMBER,
    AccountID NUMBER,
    ActionDate DATE,
    Action VARCHAR2(100)
);

-------------------------------------------------
-- Scenario 1 : Update Customer Last Modified
-------------------------------------------------

CREATE OR REPLACE TRIGGER UpdateCustomerLastModified
BEFORE UPDATE ON Customers
FOR EACH ROW
BEGIN
    :NEW.LastModified := SYSDATE;
END;
/

-------------------------------------------------
-- Scenario 2 : Log Transactions
-------------------------------------------------

CREATE OR REPLACE TRIGGER LogTransaction
AFTER INSERT ON Transactions
FOR EACH ROW
BEGIN
    INSERT INTO AuditLog
    (
        TransactionID,
        AccountID,
        ActionDate,
        Action
    )
    VALUES
    (
        :NEW.TransactionID,
        :NEW.AccountID,
        SYSDATE,
        'Transaction Inserted'
    );
END;
/

-------------------------------------------------
-- Scenario 3 : Check Transaction Rules
-------------------------------------------------

CREATE OR REPLACE TRIGGER CheckTransactionRules
BEFORE INSERT ON Transactions
FOR EACH ROW
DECLARE
    v_balance NUMBER;
BEGIN

    SELECT Balance
    INTO v_balance
    FROM Accounts
    WHERE AccountID = :NEW.AccountID;

    IF :NEW.TransactionType = 'Withdrawal' THEN

        IF :NEW.Amount > v_balance THEN
            RAISE_APPLICATION_ERROR(-20001,
            'Withdrawal exceeds account balance.');
        END IF;

    ELSIF :NEW.TransactionType = 'Deposit' THEN

        IF :NEW.Amount <= 0 THEN
            RAISE_APPLICATION_ERROR(-20002,
            'Deposit amount must be positive.');
        END IF;

    END IF;

END;
/

-------------------------------------------------
-- Test Trigger 1
-------------------------------------------------

UPDATE Customers
SET Balance = 5000
WHERE CustomerID = 1;

-------------------------------------------------
-- Test Trigger 2
-------------------------------------------------

INSERT INTO Transactions
VALUES
(
    3,
    1,
    SYSDATE,
    500,
    'Deposit'
);

-------------------------------------------------
-- Verify Results
-------------------------------------------------

SELECT * FROM Customers;

SELECT * FROM AuditLog;

SELECT * FROM Transactions;